In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('Clean Data_1.csv')

In [4]:
df.head()

,Unnamed: 0,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),...,STDs:HIV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0
1,1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0
2,2,34,1.0,16.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0
3,3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,...,0.0,0,1,0,1,0,0,0,0,0
4,4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,...,0.0,0,0,0,0,0,0,0,0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 856 entries, 0 to 855
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unnamed: 0                       856 non-null    int64
 1   Age                              856 non-null    int64
 2   Number of sexual partners        856 non-null    float64
 3   First sexual intercourse         856 non-null    float64
 4   Num of pregnancies               856 non-null    float64
 5   Smokes                           856 non-null    float64
 6   Smokes (years)                   856 non-null    float64
 7   Smokes (packs/year)              856 non-null    float64
 8   Hormonal Contraceptives          856 non-null    float64
 9   Hormonal Contraceptives (years)  856 non-null    float64
 10  IUD                              856 non-null    float64
 11  IUD (years)                      856 non-null    float64
 12  STDs                             856 non-null    float64
 13  STDs:condylomatosis              856 non-null    float64
 14  STDs:syphilis                    856 non-null    float64
 15  STDs:HIV                         856 non-null    float64
 16  STDs: Number of diagnosis        856 non-null    int64
 17  Dx:Cancer                        856 non-null    int64
 18  Dx:CIN                           856 non-null    int64
 19  Dx:HPV                           856 non-null    int64
 20  Dx                               856 non-null    int64
 21  Hinselmann                       856 non-null    int64
 22  Schiller                         856 non-null    int64
 23  Citology                         856 non-null    int64
 24  Biopsy                           856 non-null    int64
dtypes: float64(14), int64(11)
memory usage: 167.3 KB